version: '3.8'

services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ${PWD}/data/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - ml-network

  mongodb-compass:
    image: mongo-express:1.0.0-18-alpine3.18
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "root"
      ME_CONFIG_BASICAUTH_USERNAME: "root"
      ME_CONFIG_BASICAUTH_PASSWORD: "root"
    ports:
      - "8081:8081" # INTERFACE: http://localhost:8081
    networks:
      - ml-network

  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # INTERFACE: http://localhost:8080
    volumes:
      - ./app:/app
    environment:
      MONGO_HOST: "mongo"
      MONGO_PORT: "27017"
      MONGO_USER: "root"
      MONGO_PASSWORD: "root"
    networks:
      - ml-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  ml-network:
