version: '3.8'

services:
  mongo:
    extends:
      file: docker-compose-base.yml
      service: mongo
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 256M
    labels:
      kompose.service.type: "LoadBalancer"

  mongodb-compass:
    extends:
      file: docker-compose-base.yml
      service: mongodb-compass
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 256M
    labels:
      kompose.service.type: "LoadBalancer"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo-tcp"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "root"
      ME_CONFIG_BASICAUTH_USERNAME: "root"
      ME_CONFIG_BASICAUTH_PASSWORD: "root"

  streamlit:
    extends:
      file: docker-compose-base.yml
      service: streamlit
    image: gcr.io/<project_id>/mystreamlitconfig:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    environment:
      MONGO_HOST: "mongo-tcp"
      MONGO_PORT: "27017"
      MONGO_USER: "root"
      MONGO_PASSWORD: "root"
    labels:
      kompose.service.type: "LoadBalancer"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://streamlit-tcp:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  ml-network:
