apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prd.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: mongodb-compass
  name: mongodb-compass
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-compass
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prd.yml
        kompose.service.type: LoadBalancer
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: mongodb-compass
    spec:
      containers:
        - env:
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: root
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: root
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: root
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongo-tcp
          image: mongo-express:1.0.0-18-alpine3.18
          name: mongodb-compass
          ports:
            - containerPort: 8081
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: "268435456"
            requests:
              cpu: 100m
              memory: "268435456"
      restartPolicy: Always
