apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-prd.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: streamlit
  name: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streamlit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-prd.yml
        kompose.service.type: LoadBalancer
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: streamlit
    spec:
      containers:
        - env:
            - name: MONGO_HOST
              value: mongo-tcp
            - name: MONGO_PASSWORD
              value: root
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USER
              value: root
          image: gcr.io/<project_id>/mystreamlitconfig:latest
          livenessProbe:
            exec:
              command:
                - curl -f http://streamlit-tcp:8080/ || exit 1
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          name: streamlit
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 250m
              memory: "536870912"
            requests:
              cpu: 100m
              memory: "268435456"
      restartPolicy: Always
